# Generated by Django 3.1.7 on 2021-03-02 11:54

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assigner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.TextField(default=datetime.datetime(2021, 3, 2, 11, 54, 49, 114808, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='industry',
            field=models.CharField(choices=[('fianace', 'Fianace'), ('health care', 'Health Care'), ('insurance', 'Insurance'), ('manufacturing', 'Manufacturing'), ('publishing', 'Publishing')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='website',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
    ]
