# Generated by Django 3.1.7 on 2021-03-02 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in process', 'In Process'), ('converted', 'Converted'), ('recycle', 'Recycle'), ('dead', 'Dead')], max_length=50)),
                ('source', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('existence', 'Existence'), ('partner', 'Partner'), ('public', 'Public'), ('compaign', 'Compaign')], max_length=50)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField()),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('enqueryType', models.CharField(max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.account')),
                ('assigned_to', models.ManyToManyField(max_length=100, to=settings.AUTH_USER_MODEL)),
                ('created_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
