# Generated by Django 3.1.7 on 2021-03-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0002_lead_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='image',
            field=models.ImageField(default='images/girl.png', upload_to='images/'),
        ),
    ]
