# Generated by Django 3.1.7 on 2021-03-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0003_auto_20210304_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='image',
            field=models.ImageField(blank=True, default='images/girl.png', null=True, upload_to='images/'),
        ),
    ]
