# Generated by Django 3.1.7 on 2021-03-04 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20210302_1524'),
        ('Lead', '0004_auto_20210304_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.account'),
        ),
    ]
